import type { LucideIcon } from "lucide-react";
import {
  AlarmClockCheck,
  ArrowLeftRight,
  Banknote,
  Blocks,
  Box,
  BriefcaseBusiness,
  Building2,
  CreditCard,
  DollarSign,
  FolderCog,
  Gauge,
  LayoutDashboard,
  Package,
  Receipt,
  ScrollText,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Store,
  Trash2,
  Truck,
  Users,
  UserCheck,
  UserX,
  Wallet,
} from "lucide-react";

export const iconMap = {
  dashboard: LayoutDashboard,
  inventory: Package,
  products: Box,
  categories: Blocks,
  brands: BriefcaseBusiness,
  stockOverview: Store,
  lowStock: AlarmClockCheck,
  alertRecords: ShieldCheck,
  stockMovements: ArrowLeftRight,
  transfers: Truck,
  sales: ShoppingCart,
  newSale: Receipt,
  soldItems: ShoppingBag,
  salesList: ScrollText,
  customers: Users,
  customerCredit: CreditCard,
  customerPayments: Wallet,
  purchases: ShoppingBag,
  newPurchase: Receipt,
  purchaseList: ScrollText,
  suppliers: Truck,
  supplierPayments: Banknote,
  sellers: Users,
  accounts: Wallet,
  cashTransfers: ArrowLeftRight,
  expenses: DollarSign,
  reports: Gauge,
  admin: FolderCog,
  branches: Building2,
  settings: Settings,
  trash: Trash2,
  users: Users,
  userCheck: UserCheck,
  userX: UserX,
  roles: ShieldCheck,
  ledger: ScrollText,
  auditLogs: ScrollText,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;

export function getIcon(name: IconName) {
  return iconMap[name];
}
